# Gunakan base image Node.js yang cocok
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Tambahkan ini untuk membangun ulang native modules dalam konteks Linux
RUN npm rebuild

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
