services:
  database:
    image: postgres:15
    container_name: postgres_ist
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_ist
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: frontend_isi
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
    command: ./entrypoint.sh

volumes:
  pgdata:
